### ISSUE TITLE
Consultation issue for the Class KafkaWriteClickHouse

### ISSUE THREAD

**Issue by ArkNg** [liuhouer/np-flinks#1]
Hi 博主好
偶然在b站刷到你的视频，最近正在学习flink，想自己实现一个flink消费kafka数据写入Clickhouse的场景，
想请教下代码中的KafkaConsumer类，在企业里是都会单独实现吗？配置信息一般要写在哪里呢？
src/main/java/cn/northpark/flink/clickhouse/KafkaWriteClickHouse.java

**Comment by liuhouer** [comment]
> Hi 博主好 偶然在b站刷到你的视频，最近正在学习flink，想自己实现一个flink消费kafka数据写入Clickhouse的场景， 想请教下代码中的KafkaConsumer类，在企业里是都会单独实现吗？配置信息一般要写在哪里呢？ src/main/java/cn/northpark/flink/clickhouse/KafkaWriteClickHouse.java

kafka配置一般写在配置文件，或者数据库配置表。
至于Kafka的消费，可以抽象一下。也可以直接写在函数中，比较灵活。没有特殊要求

**Comment by ArkNg** [comment]
回复的好快！感谢！最近正在看这部分准备跟着敲一遍.. 最近面试被迫学flink... 
另外还想问下博主，关于flink这部分API和flink sql属于独立的两部分吗？我想在短期内快速了解，但是网上的一些例子比如建表什么的有点儿抽象
